# Generated by Django 2.2.7 on 2019-11-28 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20191128_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsm',
            name='image_links',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
