# Generated by Django 2.2.7 on 2019-11-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20191128_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsm',
            name='image_links',
            field=models.TextField(blank=True, null=True),
        ),
    ]
