# Generated by Django 2.2.7 on 2019-11-28 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20191128_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsm',
            name='rubric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Rubric'),
        ),
    ]
