# Generated by Django 2.2.7 on 2019-11-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_newsm_rubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='newsm',
            name='image_links',
        ),
        migrations.AddField(
            model_name='newsm',
            name='image_links',
            field=models.ManyToManyField(to='news.Images'),
        ),
    ]
